### ISSUE TITLE
webpage link to viewer

### ISSUE THREAD

**Issue by Jordiid** [ICATMAR/VISAP#19]
The webpage of ICATMAR cannot enter to the viewer when the language is set to English.

**Comment by jordi-ribera** [comment]
I didn't see the issue as nobody was assigned to it. I haven't been able to reproduce the issue, though. 
I have checked the access of the fisheries viewer from the www.icatmar.cat website in English (https://icatmar.cat/en/viewers/fishery-viewer/) and it's working.
