### ISSUE TITLE
in port_biomass.json and season_biomass.json add if the species is target or not

### ISSUE THREAD

**Issue by gerardllorach** [ICATMAR/VISAP#27]

**Comment by jordi-ribera** [comment]
A target label was added to the catch composition and length distribution data for OTB and PS. I am reassigning the feature to finish the integration of the target species as a filter of the species selector.

**Comment by gerardllorach** [comment]
remove merluccius from purse seine data, remove seitó and sardina as target species from bottom trawling...
do the same for other species (as it was done in issue #33)

**Comment by jordi-ribera** [comment]
I am reassigning the feature to finish the integration of the target species as a filter of the species selector in the catch composition product
