### ISSUE TITLE
switch to tonnes in purse-seine

### ISSUE THREAD

**Issue by gerardllorach** [ICATMAR/VISAP#30]

**Comment by jordi-ribera** [comment]
The catch composition files for PS have been switched to tonnes, as well as the functions to prepare the data (PieChart.js). Rendering the correct units depending on the fishing gear is missing (kg/km2 for OTB and t for PS)

**Comment by gerardllorach** [comment]
fixed in b30863c7f4a345d8d0414e10f22a236c3d4a4aa6

still need to adjust the y-label and tooltip in length distribution

**Comment by gerardllorach** [comment]
fixed in eadfb0fb26be534411a246eae3290af325b671d0 (now it is in percentages)
