### ISSUE TITLE
Unit changes for PS in catch composition

### ISSUE THREAD

**Issue by jordi-ribera** [ICATMAR/VISAP#42]
- Catch composition per season and port should be labeled as kg / haul (data is already in kg per haul).
- Catch composition per haul (map) should be labeled as kg (data is already in kg).

**Comment by gerardllorach** [comment]
Tanco l'issue, està solucionat aquí:
0608cf31b186ed3e420b75c580c6dcf82e811881

**Comment by jordi-ribera** [comment]
fixed in commit a81bb4e
