### ISSUE TITLE
classification is null in haul file 24052.json

### ISSUE THREAD

**Issue by gerardllorach** [ICATMAR/VISAP#45]
For some reason there is no classification in this haul. I haven't checked others (will do now).

![image](https://github.com/user-attachments/assets/480f3ccf-fbaa-4f39-8ce3-4a5b53717974)

**Comment by gerardllorach** [comment]
21901

![image](https://github.com/user-attachments/assets/aa187344-0907-4ba9-ba66-0578e31bd974)

**Comment by gerardllorach** [comment]
I only found these two

**Comment by jordi-ribera** [comment]
These two hauls were released fish. Sometimes the fishing operation is performed but for some reasons (e.g. small size) the catch is released back to the sea without being fished. In these situations, we take a sample of what was released. The DB query was updated to filter the hauls where fish were released.
