### ISSUE TITLE
[Feature] Integrate data from purse seine

### ISSUE THREAD

**Issue by gerardllorach** [ICATMAR/VISAP#9]
- trackPoints.json or similar to get the locations of purse seine
- catch composition graphs will change
- effort map
- ...

**Comment by gerardllorach** [comment]
working on it in commi e742bbcb4f1afc01152e421961d55ab9d027c853

Files where the paths were modified:
- AppLengthFreq.vue
- FishingEffort.vue
- HaulInfo.vue
- Map.vue
- PiechartSection.vue

Now working on this files and creating reactivity from the modalities menu

**Comment by gerardllorach** [comment]
@jordi-ribera The ranges for the effort maps of purse seine are missing. I could extract 140 h per km2 and 28K kg/km2 from the word document. 

[Visualization of purse seine sampling.docx](https://github.com/user-attachments/files/16628087/Visualization.of.purse.seine.sampling.docx)

**Comment by gerardllorach** [comment]
I also changed the paths of the fishing efforts, the hauls etc... This will have to be updated in the VISAPI repositori (nodejs api)

**Comment by gerardllorach** [comment]
> @jordi-ribera The ranges for the effort maps of purse seine are missing. I could extract 140 h per km2 and 28K kg/km2 from the word document. No range for the euros?
> 
> [Visualization of purse seine sampling.docx](https://github.com/user-attachments/files/16628087/Visualization.of.purse.seine.sampling.docx)

Now I see I have some images showing the legends with the ranges. I will use these

**Comment by gerardllorach** [comment]
purse seine hauls:
21901.json --> classification = null
22009.json --> empty json
18413.json --> empty json

**Comment by gerardllorach** [comment]
map section mostly working with commit 7f84aa4e7f88b1c784f9484ef20fc526804c7dd3. There are some internal processings that could be optimized, but the map is working now for trawling and purse-seine.

**Comment by gerardllorach** [comment]
catch composition (overview) loaded with the two modalities
commit 5bc85fb
- Change units of the pie chart?
- Numbers are too big to understand (should be expressed in tonnes or kilotonnes?)

**Comment by jordi-ribera** [comment]
> purse seine hauls: 21901.json --> classification = null 22009.json --> empty json 18413.json --> empty json

I have checked the empty jsons and these are hauls where they released the catch. I will discuss it with the PS team to evaluate if we filter these hauls.

**Comment by jordi-ribera** [comment]
hauls released where filtered in commit f8a98a1
